---
title: "CodeBook"
author: "Phillip Rowe"
date: "7/27/2019"
output: 
     md_document: 
          variant: markdown_github
---

## CodeBook for Getting and Cleaning Data Course Project

This CodeBook describes the variables, the data, and any transformations or work that was performed to clean up the data for the Course Project.

The source data inlcudes a number of raw data files and descriptive information that is not actually needed or used to perform the cleaning and preparation of the final tidy data set.  Thus, we will discuss only the files and data used in this process.

In the first section, we discuss the 9 Data Source files actually used.  Then, we described the variables in the final tidy data set, from tidy_data.txt.

### Data Source

The dataset downloaded for cleaning was the Human Activity Recognition Using Smartphones Dataset, Version 1.0, via the link to in the Coursera materials [**here**].(https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip).  The download process was automated in the R script.

The files used include the following 9 files:

* **activity_label.txt** - a simple file showing the mapping of numbered activity labels to its descriptive label. Each subject/person performed six activities during the experiment (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING).  This was eventually used to transform the numbered labels in the y_train.txt and y_test.txt files to the descriptive label, which is required for the final tidy data set. For specifics of this transformation, see step 3 of the README.md file.
* **features.txt** - a numbered list of 561 feature variables for the X_test and X_train files, generated from the three-axis accelerometer and gyroscope data readings of the experiments (Human Activity Recognition Using Smartphones Dataset, Version 1.0).  The X_train.txt and X_test.txt data is unlabeled, so the features.txt file is used to match the columns of the X data with variable names.  
* **features_info.txt** - This file describes the background of how the 561 variables were derived from raw experimental data, but since we did not do any processing of the data, we did not use this file other than to understand how to filter for mean and standard deviation variables.

The remaining 6 files are described below in an excerpt from the README.md file.

#### Excerpt from README: 1. Merging the training and the test sets to create one data set

The test and training datasets are spread out over the 6 files bulleted below.  My script loads all these files into dataframes using the read.delim() function, adds an index column to the dataframes, and then performs two separate merges on the index columns: first, to connect the 'y' and 'subject' dataframes, and second, to add on the 'x' variables.  These two merges are done for both the training and test data sets.  We should also note that the X dataframes are given descriptive variable names from the features.txt file.

The dataframes `test_data` and `train_data` are then combined into all_data using rbind().  The ```all_data``` dataframe has 10,299 rows x 564 columns (rows = combined rows of test and training data, columns = index, subject, y_numlabels, 561 feature variables).

* **y_test.txt :** 2,947 observations(rows) and 1 column with a number label (1-6) for the activity performed by the experimental subjects.  There are 9 subjects (2, 4, 9, 10, 12, 13, 18, 20, and 24) included vs. a total of 30, so 30% of the data were for the test data set and the remaining 21 subjects (70%) were part of the training set.  
* **subject_test.txt :** 2,947 rows x 1 column with numbered label (1-30) of subject who performed the activity.
* **X_test.txt :** 2,947 observations(rows) x 561 columns of feature variables.  For each subject, two experiments were run, each of about 163 rows (i.e., 163 rows x 9 subjects x 2 experiments = 2,934 total rows).  Due to sampling and how the experiments were manually labeled, the samples or rows are not exactly the same from experiment to experiment. Features are normalized and bounded within [-1,1].

* **y_train.txt :** 7,352 rows x 1 column. 
* **subject_train.txt :** 7,352 rows x 1 column, with numbered label (1-30) of subject who performed the activity.
* **X_train.txt :** 7,352 rows x 561 columns. There were 21 subjects included in this dataset, each with 2 experiments, which comes to about 175 samples(or rows) per experiment. Features are normalized and bounded within [-1,1].

An overview of the 561 feature variables in X_train, X_test, and all_data can be found at the bottom of this document, but because most are excluded from the tidy data set and are not transformed in any way, we will not provide a full description of all 561. The names of the 79 variables (46 mean variables and 33 standard deviation variables) that end up in the mean_by_activity tidy data set are are included in the Appendix, however.

### Tidy_data.txt variables 

The tidy_data.txt file is 180 rows by 81 columns, showing the calculated mean value for 79 variables for each activity x subject pair (6 activities x 30 subjects = 180 rows).  A full description of how the source data was processed to get the final data can be found in README.md. 

|  Activity |  Subject  | 46 mean variables | 33 standard deviation variables |
|--------|:---------:|:---------:|:---------:|  
| 1 of 6 descriptive labels | 1-30 | 46 calculated averages for given activity/label | 33 calculated averages for given activity/label |

#### 79 Feature Variables Extracted from 561 Feature Variables 

As stated previously, the consolidated data from X_test and X_train files contains 561 variables generated from the three-axis accelerometer and gyroscope data readings of the experiments (Human Activity Recognition Using Smartphones Dataset, Version 1.0).  Only 79 of these variables were extracted, including 46 mean variables and 33 standard deviation variables, that end up in the **tidy_data.txt** file.  As shown under heading 5 of the README.md file, the first two columns of the ```mean_by_activity``` dataframe and tidy_data.txt are Activity and Subject variables, so there are a total of 81 columns.

**Mean variables (46)**

Appearing in following order as Columns 3-48 in ```mean_by_activity``` dataframe or in tidy_data.txt.

| 1-16    | 17-32    |  33-46      |
|--------|:---------:|:---------:|
| tBodyAcc_mean_X | tGravityAccMag_mean | fBodyGyro_mean_X | 
 | tBodyAcc_mean_Y | tBodyAccJerkMag_mean | fBodyGyro_mean_Y | 
 | tBodyAcc_mean_Z | tBodyGyroMag_mean | fBodyGyro_mean_Z | 
 | tGravityAcc_mean_X | tBodyGyroJerkMag_mean | fBodyGyro_meanFreq_X | 
 | tGravityAcc_mean_Y | fBodyAcc_mean_X | fBodyGyro_meanFreq_Y | 
 | tGravityAcc_mean_Z | fBodyAcc_mean_Y | fBodyGyro_meanFreq_Z | 
 | tBodyAccJerk_mean_X | fBodyAcc_mean_Z | fBodyAccMag_mean | 
 | tBodyAccJerk_mean_Y | fBodyAcc_meanFreq_X | fBodyAccMag_meanFreq | 
 | tBodyAccJerk_mean_Z | fBodyAcc_meanFreq_Y | fBodyBodyAccJerkMag_mean | 
 | tBodyGyro_mean_X | fBodyAcc_meanFreq_Z | fBodyBodyAccJerkMag_meanFreq | 
 | tBodyGyro_mean_Y | fBodyAccJerk_mean_X | fBodyBodyGyroMag_mean | 
 | tBodyGyro_mean_Z | fBodyAccJerk_mean_Y | fBodyBodyGyroMag_meanFreq | 
 | tBodyGyroJerk_mean_X | fBodyAccJerk_mean_Z | fBodyBodyGyroJerkMag_mean | 
 | tBodyGyroJerk_mean_Y | fBodyAccJerk_meanFreq_X | fBodyBodyGyroJerkMag_meanFreq | 
 | tBodyGyroJerk_mean_Z | fBodyAccJerk_meanFreq_Y | 
 | tBodyAccMag_mean | fBodyAccJerk_meanFreq_Z | 

**Standard deviation variables (33)**

Appearing in order as Columns 49-81 in mean_by_activity dataframe or in tidy_data.txt.

| 1-11    | 12-22    |  23-33     |
|--------|:---------:|:---------:|
 | tBodyAcc_std_X | tBodyGyro_std_Z | fBodyAcc_std_Z | 
 | tBodyAcc_std_Y | tBodyGyroJerk_std_X | fBodyAccJerk_std_X | 
 | tBodyAcc_std_Z | tBodyGyroJerk_std_Y | fBodyAccJerk_std_Y | 
 | tGravityAcc_std_X | tBodyGyroJerk_std_Z | fBodyAccJerk_std_Z | 
 | tGravityAcc_std_Y | tBodyAccMag_std | fBodyGyro_std_X | 
 | tGravityAcc_std_Z | tGravityAccMag_std | fBodyGyro_std_Y | 
 | tBodyAccJerk_std_X | tBodyAccJerkMag_std | fBodyGyro_std_Z | 
 | tBodyAccJerk_std_Y | tBodyGyroMag_std | fBodyAccMag_std | 
 | tBodyAccJerk_std_Z | tBodyGyroJerkMag_std | fBodyBodyAccJerkMag_std | 
 | tBodyGyro_std_X | fBodyAcc_std_X | fBodyBodyGyroMag_std | 
 | tBodyGyro_std_Y | fBodyAcc_std_Y | fBodyBodyGyroJerkMag_std | 
